apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: allow-only-ghcrio-vojtechmares-examples-images
spec:
  images:
  - glob: "ghcr.io/vojtechmares-examples/kcd-bratislava-2025-oci-attestations/**"
  authorities:
  - static:
      action: pass
