apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: only-images-signed-with-demo-key
spec:
  images:
  - glob: "**"
  authorities:
  - name: image-signed
    key:
      secretRef:
        name: cosign-pubkey
